Repository acc-agvaldezc/Loading-FJ, pull requests merged in 2018-02, with the labels that each got.

#34 creted the last screen
  src/app/app.component.html
  src/app/app.module.ts
  src/app/lastscreen/lastscreen.component.css
  src/app/lastscreen/lastscreen.component.html
  src/app/lastscreen/lastscreen.component.spec.ts
  src/app/lastscreen/lastscreen.component.ts
Labels: enhancement

#35 observables insted of localstorage
  src/app/journeys/journeys.component.html
  src/app/journeys/journeys.component.ts
  src/app/journeys/task-accordion.component.ts
  src/app/services/journeys.service.ts
Labels: bugfix

#36 Lots of Changes
  src/app/app.component.html
  src/app/app.module.ts
  src/app/gallery/gallery.component.css
  src/app/gallery/gallery.component.html
  src/app/gallery/gallery.component.ts
  src/app/grafico/grafico.component.ts
  src/app/journeys/hours.pipe.ts
  src/app/journeys/journeys.module.ts
  src/app/journeys/task-accordion.component.css
  src/app/journeys/task-accordion.component.html
  src/app/journeys/task-accordion.component.ts
  src/app/lastscreen/lastscreen.component.css
  src/app/lastscreen/lastscreen.component.html
  src/app/lastscreen/lastscreen.component.ts
  src/app/router/journey-routing.module.ts
  src/app/services/journeys.service.ts
  src/app/shared/navbar/navbar.component.css
  src/app/shared/navbar/navbar.component.html
  src/app/shared/navbar/navbar.component.ts
  src/app/welcome/banner/banner.component.css
  src/app/welcome/banner/banner.component.html
  src/app/welcome/banner/banner.component.ts
  src/app/welcome/descripcion/descripcion.component.html
  src/assets/images/jd.png
  src/styles.css
Labels: bugfix, enhancement

#37 Guard for journeys as well as routing between task and last screen component
  src/app/gallery/gallery.component.css
  src/app/journeys/journeys.module.ts
  src/app/journeys/task-accordion.component.css
  src/app/journeys/task-accordion.component.html
  src/app/journeys/task-accordion.component.ts
  src/app/lastscreen/lastscreen.component.css
  src/app/lastscreen/lastscreen.component.html
  src/app/lastscreen/lastscreen.component.ts
  src/app/router/journey-routing.module.ts
  src/app/services/route-guard.service.ts
Labels: enhancement

#38 code refactored, follow task, mark as started/completed task, and som…
  src/app/gallery/gallery.component.html
  src/app/gallery/gallery.component.ts
  src/app/grafico/grafico.component.ts
  src/app/journeys/journeys.component.ts
  src/app/journeys/task-accordion.component.css
  src/app/journeys/task-accordion.component.html
  src/app/journeys/task-accordion.component.ts
  src/app/lastscreen/lastscreen.component.css
  src/app/lastscreen/lastscreen.component.html
  src/app/lastscreen/lastscreen.component.ts
  src/app/services/journeys.service.ts
Labels: bug

#39 the first part of unit test
  src/app/app.component.spec.ts
  src/app/gallery/gallery.component.spec.ts
  src/app/google-maps/google-maps.component.spec.ts
  src/app/grafico/grafico.component.spec.ts
  src/app/grafico/grafico.component.ts
  src/app/guards/auth.guard.spec.ts
  src/app/journeys/journeys.component.spec.ts
  src/app/lastscreen/lastscreen.component.spec.ts
  src/app/services/auth.service.spec.ts
  src/app/services/journeys.service.spec.ts
  src/app/shared/footer/footer.component.spec.ts
  src/app/shared/navbar/navbar.component.spec.ts
  src/app/welcome/banner/banner.component.spec.ts
  src/app/welcome/descripcion/descripcion.component.spec.ts
  src/app/welcome/welcome.component.spec.ts
Labels: enhancement

#41 Second sprint completion
  src/app/journeys/journeys.component.html
  src/app/journeys/journeys.component.ts
  src/app/journeys/task-accordion.component.css
  src/app/journeys/task-accordion.component.html
  src/app/journeys/task-accordion.component.ts
  src/app/lastscreen/lastscreen.component.css
  src/app/lastscreen/lastscreen.component.html
  src/app/lastscreen/lastscreen.component.ts
  src/app/services/journeys.service.ts
  src/app/shared/navbar/navbar.component.css
  src/app/shared/navbar/navbar.component.html
  src/app/shared/navbar/navbar.component.ts
  src/assets/images/team.PNG
  src/index.html
  src/styles.css
Labels: bug, enhancement
